import { getSession } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";
import Link from "next/link";
import { Brain, Search, DatabaseZap, Clock, Award } from "lucide-react";

export default async function TestsIndexPage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
  const session = await getSession();
  if (!session) redirect("/login");

  const resolvedSearchParams = await searchParams;
  const queryParam = resolvedSearchParams?.q;
  const query = typeof queryParam === "string" ? queryParam : "";

  const tests = await prisma.test.findMany({
    where: {
      userId: session.userId,
      ...(query ? { title: { contains: query, mode: "insensitive" } } : {}),
    },
    orderBy: { createdAt: "desc" },
    include: {
      _count: { select: { questions: true } },
      note: { select: { title: true } },
      attempts: { 
        where: { userId: session.userId },
        orderBy: { score: "desc" },
        take: 1
      }
    },
  });

  return (
    <main className="flex-1 flex flex-col p-6 md:p-10 gap-6">
      <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold">Your Tests</h1>
          <p className="text-zinc-400 text-sm mt-1">Quizzes generated by Gemini from your Notes.</p>
        </div>
      </header>

      {/* Search Bar */}
      <div className="relative max-w-md">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-zinc-500" />
        <form>
          <input
            type="search"
            name="q"
            placeholder="Search tests..."
            defaultValue={query}
            className="w-full rounded-xl border border-white/10 bg-white/5 py-2.5 pl-10 pr-4 text-sm text-white placeholder:text-zinc-500 focus:border-indigo-500/50 focus:outline-none focus:ring-1 focus:ring-indigo-500/50"
          />
        </form>
      </div>

      {tests.length === 0 ? (
        <div className="flex flex-1 items-center justify-center border border-dashed border-white/10 rounded-2xl bg-white/[0.02] py-20 mt-4">
          <div className="text-center p-6 max-w-sm">
            <div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-[20px] bg-indigo-500/10 border border-indigo-500/20">
              <DatabaseZap className="h-8 w-8 text-indigo-400" />
            </div>
            <p className="text-white font-semibold text-lg mb-2">No tests generated yet.</p>
            <p className="text-zinc-400 text-sm mb-6">Open any Note and click "Generate Test" to harness the power of AI to quiz your knowledge.</p>
            <Link href="/dashboard/notes" className="rounded-xl bg-white px-5 py-2.5 text-sm font-semibold text-black transition hover:bg-zinc-200">
              Go to Notes
            </Link>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4 mt-2">
          {tests.map((test) => {
            const bestAttempt = test.attempts[0];
            
            return (
              <div
                key={test.id}
                className="flex flex-col rounded-2xl border border-white/10 bg-white/5 p-6 transition hover:border-indigo-500/50"
              >
                <div className="flex items-start justify-between gap-4">
                  <h3 className="font-semibold text-lg line-clamp-2 leading-tight">
                    {test.title}
                  </h3>
                  {test.isPublic && (
                    <span className="shrink-0 text-[10px] font-bold uppercase tracking-wider bg-emerald-500/20 text-emerald-400 px-2 py-1 rounded-md">
                      Public
                    </span>
                  )}
                </div>
                
                <p className="mt-2 text-sm text-zinc-400 flex items-center gap-1.5">
                  Based on: <Link href={`/dashboard/notes/${test.noteId}`} className="text-indigo-400 hover:underline truncate">{test.note.title}</Link>
                </p>

                <div className="mt-5 grid grid-cols-2 gap-3 mb-6">
                  <div className="flex items-center gap-2 bg-black/40 rounded-lg py-2 px-3 border border-white/5">
                    <Brain className="h-4 w-4 text-zinc-500" />
                    <span className="text-sm font-medium">{test._count.questions} Qs</span>
                  </div>
                  {bestAttempt ? (
                    <div className="flex items-center gap-2 bg-indigo-500/10 rounded-lg py-2 px-3 border border-indigo-500/20">
                      <Award className="h-4 w-4 text-indigo-400" />
                      <span className="text-sm font-bold text-indigo-300">{bestAttempt.score}/{test._count.questions}</span>
                    </div>
                  ) : (
                    <div className="flex items-center gap-2 bg-black/40 rounded-lg py-2 px-3 border border-white/5">
                      <Clock className="h-4 w-4 text-zinc-500" />
                      <span className="text-sm font-medium text-zinc-400">Not taken</span>
                    </div>
                  )}
                </div>

                <div className="mt-auto flex w-full gap-2">
                  <Link
                    href={`/dashboard/tests/${test.id}`}
                    className="flex-1 text-center rounded-xl bg-indigo-500 px-4 py-2.5 text-sm font-bold text-white shadow-[0_0_10px_rgba(99,102,241,0.3)] transition hover:bg-indigo-400 group-hover:shadow-[0_0_15px_rgba(99,102,241,0.6)]"
                  >
                    Play Test
                  </Link>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </main>
  );
}
